aws:
  aws_account: development
  bucket: example-chainstorage-bootcamp-mainnet-dev
  dlq:
    name: example_chainstorage_blocks_bootcamp_mainnet_dlq
  dynamodb:
    block_table: example_chainstorage_blocks_bootcamp_mainnet
    event_table: example_chainstorage_block_events_bootcamp_mainnet
    event_table_height_index: example_chainstorage_block_events_by_height_bootcamp_mainnet
    versioned_event_table: example_chainstorage_versioned_block_events_bootcamp_mainnet
    versioned_event_table_block_index: example_chainstorage_versioned_block_events_by_block_id_bootcamp_mainnet
cadence:
  domain: chainstorage-bootcamp-mainnet
chain:
  block_time: 13s
  event_tag:
    latest: 0
    stable: 0
  feature:
    rosetta_parser: true
  irreversible_distance: 12
config_name: bootcamp-mainnet
cron:
  disable_node_canary: true
  disable_streaming_canary: true
  disable_workflow_status: true
sla: # not effective because node canary is disabled.
  block_height_delta: 5
  block_time_delta: 1m
  out_of_sync_node_distance: 10
  time_since_last_block: 2m
  event_height_delta: 5
  event_time_delta: 1m
  time_since_last_event: 2m
  expected_workflows:
workflows:
  backfiller:
    checkpoint_size: 5000
    num_concurrent_extractors: 8
  poller:
    parallelism: 10
